#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xauth
Version  : 1.1.2
Release  : 23
URL      : https://www.x.org/releases/individual/app/xauth-1.1.2.tar.gz
Source0  : https://www.x.org/releases/individual/app/xauth-1.1.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT MIT-Opengroup
Requires: xauth-bin = %{version}-%{release}
Requires: xauth-license = %{version}-%{release}
Requires: xauth-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xau)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xmuu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xtrans)

%description
I. OVERVIEW
-----------
The xauth program is used to edit and display the authorization
information used in connecting to the X server.
The underlying "Authorization Protocol for X" is described in the

%package bin
Summary: bin components for the xauth package.
Group: Binaries
Requires: xauth-license = %{version}-%{release}

%description bin
bin components for the xauth package.


%package license
Summary: license components for the xauth package.
Group: Default

%description license
license components for the xauth package.


%package man
Summary: man components for the xauth package.
Group: Default

%description man
man components for the xauth package.


%prep
%setup -q -n xauth-1.1.2
cd %{_builddir}/xauth-1.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1650421622
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1650421622
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xauth
cp %{_builddir}/xauth-1.1.2/COPYING %{buildroot}/usr/share/package-licenses/xauth/86486fb1779766ab7d69e7240a7bf54ebb86c1ba
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xauth

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xauth/86486fb1779766ab7d69e7240a7bf54ebb86c1ba

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xauth.1
